# Generated by Django 5.2.8 on 2025-11-12 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('kcal_per_100g', models.DecimalField(decimal_places=2, help_text='Calories (kcal) pour 100g', max_digits=6)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, help_text='Protéines (g) pour 100g', max_digits=5)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, help_text='Glucides (g) pour 100g', max_digits=5)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, help_text='Lipides (g) pour 100g', max_digits=5)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Petit-déjeuner'), ('lunch', 'Déjeuner'), ('dinner', 'Dîner'), ('snack', 'Collation')], default='snack', max_length=20)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Food Logs',
                'ordering': ['date', 'meal_type'],
            },
        ),
    ]
