# Generated by Django 5.2.8 on 2025-11-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlog',
            name='grams',
        ),
        migrations.AddField(
            model_name='food',
            name='unit_type',
            field=models.CharField(choices=[('g', 'Grammes (g)'), ('ml', 'Millilitres (ml)'), ('unit', 'Unité(s)')], default='g', help_text="Type d'unité de mesure", max_length=10),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Quantité (en grammes, ml ou unités)', max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs_per_100g',
            field=models.DecimalField(decimal_places=2, help_text='Glucides (g) pour 100g/100ml/unité', max_digits=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_per_100g',
            field=models.DecimalField(decimal_places=2, help_text='Lipides (g) pour 100g/100ml/unité', max_digits=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='kcal_per_100g',
            field=models.DecimalField(decimal_places=2, help_text='Calories (kcal) pour 100g/100ml/unité', max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein_per_100g',
            field=models.DecimalField(decimal_places=2, help_text='Protéines (g) pour 100g/100ml/unité', max_digits=5),
        ),
    ]
