# Generated by Django 5.2.8 on 2025-11-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_remove_foodlog_grams_food_unit_type_foodlog_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Quantité (en grammes, ml ou unités)', max_digits=6),
        ),
    ]
