# Generated by Django 5.2.8 on 2025-11-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_recipe_recipeingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carbs_per_100g',
            field=models.DecimalField(decimal_places=2, help_text='Carbs (g) per 100g/100ml/unit', max_digits=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_per_100g',
            field=models.DecimalField(decimal_places=2, help_text='Fat (g) per 100g/100ml/unit', max_digits=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='kcal_per_100g',
            field=models.DecimalField(decimal_places=2, help_text='Calories (kcal) per 100g/100ml/unit', max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein_per_100g',
            field=models.DecimalField(decimal_places=2, help_text='Protein (g) per 100g/100ml/unit', max_digits=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='unit_type',
            field=models.CharField(choices=[('g', 'Grammes (g)'), ('ml', 'Millilitres (ml)'), ('unit', 'Unité(s)')], default='g', help_text='Unit type', max_length=10),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Quantity (in grams, ml or units)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Cooking time in minutes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(help_text='Preparation instructions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time_minutes',
            field=models.PositiveIntegerField(help_text='Prep time in minutes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=1, help_text='Number of servings'),
        ),
    ]
