# Generated by Django 5.2.8 on 2025-11-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_running_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='running_data_source',
            field=models.CharField(choices=[('manual', 'Saisie manuelle'), ('strava', 'Strava'), ('garmin', 'Garmin')], default='manual', help_text='Source des données de running pour ce profil.', max_length=10),
        ),
    ]
