# Generated by Django 5.2.8 on 2025-11-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_running_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='feature_leaderboard',
            field=models.BooleanField(default=True, help_text='Activer le module Classement'),
        ),
        migrations.AddField(
            model_name='profile',
            name='feature_nutrition',
            field=models.BooleanField(default=True, help_text='Activer le module Nutrition'),
        ),
        migrations.AddField(
            model_name='profile',
            name='feature_running',
            field=models.BooleanField(default=True, help_text='Activer le module Running'),
        ),
        migrations.AddField(
            model_name='profile',
            name='feature_workouts',
            field=models.BooleanField(default=True, help_text='Activer le module Exercices & Workouts'),
        ),
    ]