# Generated by Django 5.2.8 on 2025-11-20 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('distance_m', models.FloatField()),
                ('moving_time_s', models.IntegerField()),
                ('elapsed_time_s', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('average_speed', models.FloatField(blank=True, help_text='Vitesse moyenne en m/s', null=True)),
                ('average_pace_s_per_km', models.FloatField(blank=True, help_text='Allure moyenne en secondes / km', null=True)),
                ('elevation_gain_m', models.FloatField(blank=True, help_text='D+ en mètres', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StravaAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.BigIntegerField(blank=True, null=True)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('token_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strava_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
