# Generated by Django 5.2.8 on 2025-11-20 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='garmin_id',
            field=models.BigIntegerField(blank=True, help_text='ID activité Garmin', null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='source',
            field=models.CharField(choices=[('strava', 'Strava'), ('garmin', 'Garmin Connect')], default='strava', help_text="Source de l'activité", max_length=10),
        ),
        migrations.AlterField(
            model_name='run',
            name='strava_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='GarminAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email Garmin Connect', max_length=254)),
                ('password', models.CharField(help_text='Mot de passe Garmin Connect (chiffré)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Connexion active')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Dernière synchronisation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garmin_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
