# Generated by Django 5.2.8 on 2025-11-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0002_run_garmin_id_run_source_alter_run_strava_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='calories_burned',
            field=models.FloatField(blank=True, help_text='Calories brûlées (kcal)', null=True),
        ),
    ]
