# Generated by Django 5.2.8 on 2025-11-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0003_run_calories_burned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garminauth',
            name='email',
            field=models.EmailField(help_text='Garmin Connect email', max_length=254),
        ),
        migrations.AlterField(
            model_name='garminauth',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active connection'),
        ),
        migrations.AlterField(
            model_name='garminauth',
            name='last_sync',
            field=models.DateTimeField(blank=True, help_text='Last sync', null=True),
        ),
        migrations.AlterField(
            model_name='garminauth',
            name='password',
            field=models.CharField(help_text='Garmin Connect password (encrypted)', max_length=255),
        ),
        migrations.AlterField(
            model_name='run',
            name='average_pace_s_per_km',
            field=models.FloatField(blank=True, help_text='Average pace in seconds per km', null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='average_speed',
            field=models.FloatField(blank=True, help_text='Average speed in m/s', null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='calories_burned',
            field=models.FloatField(blank=True, help_text='Calories burned (kcal)', null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='elevation_gain_m',
            field=models.FloatField(blank=True, help_text='Elevation gain in meters', null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='garmin_id',
            field=models.BigIntegerField(blank=True, help_text='Garmin activity ID', null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='source',
            field=models.CharField(choices=[('strava', 'Strava'), ('garmin', 'Garmin Connect')], default='strava', help_text='Activity source', max_length=10),
        ),
    ]
