# Generated by Django 5.2.8 on 2025-11-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.URLField(blank=True, help_text="URL de l'image de démonstration", null=True),
        ),
    ]
