# Generated by Django 5.2.8 on 2025-11-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, help_text='Image de démonstration', null=True, upload_to='exercises/'),
        ),
    ]
