# Generated by Django 5.2.8 on 2025-11-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_exercise_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Durée de la séance en minutes'),
        ),
    ]
