# Generated by Django 5.2.8 on 2025-11-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_workoutsession_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Séance terminée'),
        ),
    ]
