# Generated by Django 5.2.8 on 2025-11-19 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workoutsession_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la catégorie (ex: Musculation, Football)', max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text="Emoji ou classe d'icône (ex: 🏋️, ⚽)", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('has_specific_exercises', models.BooleanField(default=True, help_text='True si ce sport a ses propres exercices spécifiques')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie de sport',
                'verbose_name_plural': 'Catégories de sports',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('barbell', 'Barre'), ('dumbbell', 'Haltères'), ('machine', 'Machine'), ('cable', 'Poulie'), ('bodyweight', 'Poids du corps'), ('ball', 'Ballon'), ('racket', 'Raquette'), ('water', 'Eau'), ('none', 'Aucun')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(blank=True, choices=[('chest', 'Pecs'), ('back', 'Dos'), ('legs', 'Jambes'), ('shoulders', 'Épaules'), ('arms', 'Bras'), ('core', 'Abdos'), ('fullbody', 'Corps complet'), ('cardio', 'Cardio'), ('technique', 'Technique')], max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sport_category',
            field=models.ForeignKey(blank=True, help_text='Catégorie de sport de cet exercice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='workouts.sportcategory'),
        ),
    ]