# Generated by Django 5.2.8 on 2025-11-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_sportcategory_alter_exercise_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_time_based',
            field=models.BooleanField(default=False, help_text="Si True, l'exercice se mesure en temps (secondes) plutôt qu'en répétitions"),
        ),
        migrations.AddField(
            model_name='setlog',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Durée en secondes (pour exercices basés sur le temps)', null=True),
        ),
        migrations.AlterField(
            model_name='setlog',
            name='reps',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de répétitions (pour exercices non basés sur le temps)', null=True),
        ),
    ]
