# Generated by Django 5.2.8 on 2025-11-21 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_exercise_is_time_based_setlog_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Sport Category', 'verbose_name_plural': 'Sport Categories'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, help_text='Demo image', null=True, upload_to='exercises/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='is_time_based',
            field=models.BooleanField(default=False, help_text='If True, measured in time (seconds) instead of reps'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sport_category',
            field=models.ForeignKey(blank=True, help_text='Sport category for this exercise', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='workouts.sportcategory'),
        ),
        migrations.AlterField(
            model_name='setlog',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds (for time-based exercises)', null=True),
        ),
        migrations.AlterField(
            model_name='setlog',
            name='reps',
            field=models.PositiveIntegerField(blank=True, help_text='Number of reps (for non time-based exercises)', null=True),
        ),
        migrations.AlterField(
            model_name='sportcategory',
            name='has_specific_exercises',
            field=models.BooleanField(default=True, help_text='True if this sport has its own specific exercises'),
        ),
        migrations.AlterField(
            model_name='sportcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or icon class (e.g. 🏋️, ⚽)', max_length=50),
        ),
        migrations.AlterField(
            model_name='sportcategory',
            name='name',
            field=models.CharField(help_text='Category name (e.g. Weightlifting, Football)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sportcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Session duration in minutes'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Session completed'),
        ),
    ]
