# Generated by Django 5.2.8 on 2025-11-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_sportcategory_options_alter_exercise_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (for production)', null=True),
        ),
    ]
